platform :ios, '12.0'
use_frameworks!
inhibit_all_warnings!

target 'RSReactiveRequest_Example' do
    
    pod 'RSReactiveRequest', :path => '../'

    target 'RSReactiveRequest_Tests' do
        inherit! :search_paths

    end
end
