use_frameworks!

target 'RSReactiveRequest_Example' do

    use_frameworks!
    inhibit_all_warnings!

    platform :ios, '9.0'
    
    pod 'RSReactiveRequest', :path => '../'

    target 'RSReactiveRequest_Tests' do
        inherit! :search_paths

    end
end
